default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  host: localhost
  username: postgres
  database: lynyc
  password:

test:
  <<: *default
  host: localhost
  username: postgres
  database: lynyc-test
  password:

production:
  url: <%= ENV['DATABASE_URL'] %>
