# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c691ffbff577aca9ddd89eb2db6b71864995a7bbea56b35697f9088228dc14a26524193f161afecc1d6ec60781697ba9d376226d84cf1d2db74244aecd224cd2

test:
  secret_key_base: 873b16371f020e51920618be40fdc79d05b19834ebbb7fd7b077cd5f9ce277e18744ab757669ce544330b3e7c3ff3ff0f0f40acae4d5a8a68c0d33f47cc1ee70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
